### ISSUE TITLE
Steps to a stable 7.0.0

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/rust-tss-esapi#290]
Since we're currently in an alpha release (yet again) it would be good to know what we'd like to achieve before we can tag a stable release. Our focus right now is to remove all not-abstracted FFI types from the `tss-esapi` interface, replacing them with types that we have more control over.

FFI types still present in the `Context` interface (not going to link to where they appear, a simple search through the repo should be enough for that):
- [x] TPMT_SIG_SCHEME ( https://github.com/parallaxsecond/rust-tss-esapi/pull/286 )
- [x] TPM2B_ATTEST ( ~~will be lifted from https://github.com/parallaxsecond/rust-tss-esapi/pull/221~~ ; #293 covers this  )
- [x] TPMA_LOCALITY ( https://github.com/parallaxsecond/rust-tss-esapi/pull/294 )
- [x] TPM2_CC ( #296 )
- [x] TPM2B_SENSITIVE ( #306 )

Another type that currently uses other FFI types in its interface is `CapabilityData`. The types:
- [x] TPM2_PT (just replacing the use in `CapabilityData` with the existing abstraction, https://github.com/parallaxsecond/rust-tss-esapi/pull/301)
- [x] TPM2_PT_PCR (#305, #308)
- [x] TPMA_ALGORITHM (https://github.com/parallaxsecond/rust-tss-esapi/pull/304)
- [x] TPMA_CC(#315)
- [x] TPML_CCA(#315)
- [x] TPM2_ECC_CURVE ( #312  )

Other bits of work:
- [x] Identify the cause of #285 and fix it
- [x] Finish off the request in #277 ( https://github.com/parallaxsecond/rust-tss-esapi/pull/281 )
- [x] Fix PCR structures issues (#310 #311 #317 )

I was also wondering about changing a few other things, please list any other ideas/concerns below:
- [x] ~~Some key-bits types seem redundant, for example `Sm4KeyBits` can only have one value. I wonder if it wouldn't be better to just remove the type completely and have a "default" implementation that produces the correct FFI values wherever they're needed to replace the current conversions~~
- [x] For structures that can be built using `...Builder` structures, we should either document this or create a method on the type to get a new builder, something like `pub fn builder() -> ...` ( #316 )

**Comment by ionut-arm** [comment]
We should also try to identify the cause of #285  and fix it before the release. Also, #277 should be included (via https://github.com/parallaxsecond/rust-tss-esapi/pull/281 ).

**Comment by ionut-arm** [comment]
@rshearman - Do you require any specific features in the upcoming release (more specifically, `TPM2_Certify`)? We can, of course, release extra functionality in a future minor release, but I'm not sure if that's relevant to you at all (i.e. if you use crates.io for dependency management, or if git dependencies are good enough).

**Comment by rshearman** [comment]
It would be good to have TPM2_Certify in the upcoming release, but I'm decoupled from the tss-esapi release cycle. In other words, it would also be fine to have this in a future minor release.
There's nothing else I can think of that I would need in the near future.

**Comment by ionut-arm** [comment]
@Superhepper - have you, by any chance, started working on `TPM2B_SENSITIVE`? Plan on starting that tomorrow, if you're not already on it.

**Comment by Superhepper** [comment]
Nah I have not started any work on it. I plan to work on the issue with tagged PCR property list

**Comment by ionut-arm** [comment]
@Superhepper - `CapabilityData` still has `TPM2_ECC_CURVE` and `TPMA_CC` to abstract, are you looking at either of them?

**Comment by Superhepper** [comment]
Right now I am working with TPMA_CC.

**Comment by ionut-arm** [comment]
Will do the `ECC_CURVE` then. I assume that's the last of it? Have you seen anything else?

**Comment by Superhepper** [comment]
No, I usually add stuff if a find things a long the way.

**Comment by ionut-arm** [comment]
After #316 is merged are we clear to release a 7.0.0, or is there some other stuff to be done?

**Comment by Superhepper** [comment]
I maybe want to add the compilation bug for PcrSlot. But if people need a released major version rather soon. I think we can make a release without it.

**Comment by ionut-arm** [comment]
If we can get that fix in next week that would be nice, but otherwise it's not a breaking change, I think, so we can release it as a bugfix update, not even a minor bump.

**Comment by Superhepper** [comment]
Yeah, just say the release will come on Friday next week. If it makes it, it makes it otherwise it will be added later.

**Comment by ionut-arm** [comment]
@puiterwijk @lkatalin @rshearman 
Please be advised, we're planning to release a new stable version of the `tss-crate` soon. If you'd like to test any parts of the crate, or to give any feedback on the interface please do so within the next few days.

**Comment by lkatalin** [comment]
Thanks for the heads up @ionut-arm ! I just ran a test and it seems fine for us with Keylime.

**Comment by ionut-arm** [comment]
I've released a `7.0.0-beta.1` version of the `tss-crate`, the stable release will go out next week if no issues are reported until then!

**Comment by rshearman** [comment]
I've updated our application to use `7.0.0-beta.1` and in the course of that I ran into #322. The only other thing I noticed is that it would be nice if `EccCurveIdentifier` derived `Hash`, but that's something that can be easily done later.

**Comment by ionut-arm** [comment]
I've just released and tagged [tss-esapi-7.0.0-beta.2](https://github.com/parallaxsecond/rust-tss-esapi/releases/tag/tss-esapi-7.0.0-beta.2)

**Comment by ionut-arm** [comment]
The 7.0.0 stable version has been released! 🎉 Please let us know if any issues surface, so we can fix them right away!
