### ISSUE TITLE
Change minimum required tpm2-tss version.

### ISSUE THREAD

**Issue by Superhepper** [parallaxsecond/rust-tss-esapi#496]
The currently minimum supported version of ```tpm2-tss``` is ```2.3.3``` (according to the README.md in the ```-sys``` crate). This is rather old, latest release was ```2.4.6``` in  2021-05-17. So the version should be updated to probably the latest release of the lowest major version available which would be ```3.2.2```.

- [ ] Update bindgen version. #505 
- [ ] Generate new bindings using the new bindgen version and the 3.2.2 version of tpm2-tss #505 
- [ ] Update the README.md in the ```-sys``` crate. #505
